version: '3.7'

services:
  zookeeper:
   container_name: zookeeper
   image: confluentinc/cp-zookeeper:latest
   ports:
     - "9900:2181"
   environment:
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_TICK_TIME: 2000
   networks:
     - elk
    
  kafka:
   container_name: kafka
   build:
     context: kafka/
   depends_on:
     - zookeeper
   expose:
     - "9092"
   ports:
     - "9092:9092"
   environment:
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
   networks:
     - elk      
  
networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
  dump:
